# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [4]:
# Create a 1-dimensional NumPy array using np.array()
a1=np.array([1,2,3])
a1
# Create a 2-dimensional NumPy array using np.array()
a2=np.array([[1,2.,3],
             [4,5.,6],
            [7,8.5,9]
            ])
a2
# Create a 3-dimensional Numpy array using np.array()
a3=np.array([
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ],
    [[10,11,12],
    [13,14,15],
    [16,17,18]]
])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [5]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [6]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((3, 3), 2, dtype('float64'), 9, numpy.ndarray)

In [8]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int64'), 18, numpy.ndarray)

In [13]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df=pd.DataFrame(a2,columns=['one','two','three'])
df

one  two  three
0  1.0  2.0    3.0
1  4.0  5.0    6.0
2  7.0  8.5    9.0

In [18]:
# Create an array of shape (10, 2) with only ones
ones=np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
# Create an array of shape (7, 2, 3) of only zeros
zeros=np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [24]:
# Create an array within a range of 0 and 100 with step 3
range_array=np.arange(0,100, 3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [30]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array=np.random.randint(0,10,size=(7,2))
random_array

array([[5, 8],
       [7, 8],
       [8, 7],
       [4, 1],
       [3, 3],
       [0, 3],
       [4, 2]])

In [33]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array2=np.random.random(size=(3,5))
random_array2

array([[0.99704251, 0.71384687, 0.13220703, 0.11406422, 0.94225506],
       [0.5547728 , 0.20490706, 0.71322239, 0.40297951, 0.2266277 ],
       [0.00669724, 0.78100182, 0.8034601 , 0.35047933, 0.27296026]])

In [37]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array_3=np.random.randint(0,10,size=(4,6))
random_array_3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [40]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array_4=np.random.randint(1,10,size=(3,7))
random_array_4
# Find the unique numbers in the array you just created
np.unique(random_array_4)

array([1, 2, 3, 5, 7, 8, 9])

In [42]:
random_array_4

array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3],
       [1, 8, 3, 3, 1, 5, 7]])

In [41]:
# Find the 0'th index of the latest array you created
random_array_4[0]

array([2, 5, 8, 9, 9, 1, 9])

In [45]:
# Get the first 2 rows of latest array you created
random_array_4[:2]

array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3]])

In [46]:
# Get the first 2 values of the first 2 rows of the latest array
random_array_4[:2,:2]

array([[2, 5],
       [7, 9]])

In [47]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
rand_a1=np.random.randint(10,size=(3,5))
rand_a2=np.random.randint(10,size=(3,5))

In [48]:
rand_a1

array([[9, 8, 6, 8, 7],
       [1, 0, 6, 6, 7],
       [4, 2, 7, 5, 2]])

In [49]:
rand_a2

array([[0, 2, 4, 2, 0],
       [4, 9, 6, 6, 8],
       [9, 9, 2, 6, 0]])

In [50]:
# Add the two arrays together
rand_a1+rand_a2

array([[ 9, 10, 10, 10,  7],
       [ 5,  9, 12, 12, 15],
       [13, 11,  9, 11,  2]])

In [51]:
# Create another array of ones of shape (5, 3)
rand_a3=np.random.randint(10,size=(5,3))
rand_a3

array([[3, 3, 4],
       [6, 6, 3],
       [6, 2, 5],
       [1, 9, 8],
       [4, 5, 3]])

In [52]:
# Try add the array of ones and the other most recent array together
rand_a1+rand_a3

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [54]:
rand_a1+rand_a3.T

array([[12, 14, 12,  9, 11],
       [ 4,  6,  8, 15, 12],
       [ 8,  5, 12, 13,  5]])

In [55]:
# Create another array of ones of shape (3, 5)
ones=np.ones((3,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [57]:
# Subtract the new array of ones from the other most recent array
rand_a1-ones

array([[ 8.,  7.,  5.,  7.,  6.],
       [ 0., -1.,  5.,  5.,  6.],
       [ 3.,  1.,  6.,  4.,  1.]])

In [58]:
# Multiply the ones array with the latest array
rand_a1*ones

array([[9., 8., 6., 8., 7.],
       [1., 0., 6., 6., 7.],
       [4., 2., 7., 5., 2.]])

In [63]:
# Take the latest array to the power of 2 using '**'
rand_a1**ones

array([[9., 8., 6., 8., 7.],
       [1., 0., 6., 6., 7.],
       [4., 2., 7., 5., 2.]])

In [60]:
# Do the same thing with np.square()
np.square(rand_a1)

array([[81, 64, 36, 64, 49],
       [ 1,  0, 36, 36, 49],
       [16,  4, 49, 25,  4]])

In [65]:
rand_a1

array([[9, 8, 6, 8, 7],
       [1, 0, 6, 6, 7],
       [4, 2, 7, 5, 2]])

In [64]:
# Find the mean of the latest array using np.mean()
np.mean(rand_a1)

5.2

In [66]:
# Find the maximum of the latest array using np.max()
np.max(rand_a1)

9

In [67]:
# Find the minimum of the latest array using np.min()
np.min(rand_a1)

0

In [68]:
# Find the standard deviation of the latest array
np.std(rand_a1)

2.6882460204874605

In [69]:
# Find the variance of the latest array
np.var(rand_a1)

7.2266666666666675

In [72]:
# Reshape the latest array to (3, 5, 1)
rand_a1.reshape(3,5,1)
rand_a1

array([[9, 8, 6, 8, 7],
       [1, 0, 6, 6, 7],
       [4, 2, 7, 5, 2]])

In [73]:
# Transpose the latest array
rand_a1.shape, rand_a1.T.shape

((3, 5), (5, 3))

What does the transpose do?
resverse the axis

In [74]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
rand_b1=np.random.randint(0,10,size=(3,3))
rand_b2=np.random.randint(0,10,size=(3,2))

In [75]:
rand_b1

array([[9, 6, 8],
       [6, 0, 0],
       [8, 8, 3]])

In [76]:
rand_b2

array([[8, 2],
       [6, 5],
       [7, 8]])

In [83]:
# Perform a dot product on the two newest arrays you created
my_dot=np.dot(rand_b1,rand_b2)
my_dot[2][1]

80

In [84]:
my_dot

array([[164, 112],
       [ 48,  12],
       [133,  80]])

In [85]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
rand_c1=np.random.randint(1,10,size=(4,3))
rand_c2=np.random.randint(1,10,size=(4,3))

In [86]:
rand_c1

array([[5, 1, 3],
       [8, 6, 8],
       [9, 4, 1],
       [1, 4, 7]])

In [87]:
rand_c2

array([[2, 3, 1],
       [5, 1, 8],
       [1, 1, 2],
       [2, 6, 7]])

In [90]:
# Perform a dot product on the two newest arrays you created
dot_t=np.dot(rand_c1,rand_c2)
dot_t

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [91]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
dot_t=np.dot(rand_c1,rand_c2.T)
dot_t

array([[ 16,  50,  12,  37],
       [ 42, 110,  30, 108],
       [ 31,  57,  15,  49],
       [ 21,  65,  19,  75]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [92]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
rand_c1==rand_c2

array([[False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False,  True]])

In [93]:
# Compare the two arrays with '>'
rand_c1> rand_c2

array([[ True, False,  True],
       [ True,  True, False],
       [ True,  True, False],
       [False, False, False]])

What happens when you compare the arrays with `>`?

In [94]:
# Compare the two arrays with '>='
rand_c1>=rand_c2

array([[ True, False,  True],
       [ True,  True,  True],
       [ True,  True, False],
       [False, False,  True]])

In [95]:
# Find which elements of the first array are greater than 7
rand_c1>7

array([[False, False, False],
       [ True, False,  True],
       [ True, False, False],
       [False, False, False]])

In [96]:
# Which parts of each array are equal? (try using '==')
rand_c1==rand_c2

array([[False, False, False],
       [False, False,  True],
       [False, False, False],
       [False, False,  True]])

In [97]:
# Sort one of the arrays you just created in ascending order
np.sort(rand_c1)

array([[1, 3, 5],
       [6, 8, 8],
       [1, 4, 9],
       [1, 4, 7]])

In [98]:
# Sort the indexes of one of the arrays you just created
np.argsort(rand_c1)

array([[1, 2, 0],
       [1, 0, 2],
       [2, 1, 0],
       [0, 1, 2]])

In [99]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(rand_c1)

6

In [100]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(rand_c1)

1

In [101]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(rand_c1,axis=1)

array([0, 0, 0, 2])

In [102]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(rand_c1,axis=0)

array([3, 0, 2])

In [108]:
# Create an array of normally distributed random numbers
np.random.normal(100)

99.54753776765533

In [104]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.